Update io.py
report_params is a dictionary with boolean values. Using [1] is trying to insert value according to index and error is raised:
TypeError: 'bool' object does not support item assignment